# Generated by Django 5.2.5 on 2025-12-19 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0013_projectview'),
        ('Review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewee', 'rating'], name='Review_revi_reviewe_4699f3_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['project', 'reviewer'], name='Review_revi_project_227b4c_idx'),
        ),
    ]
