# Generated by Django 5.2.5 on 2025-11-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='title',
            field=models.CharField(default='Proposal', max_length=200),
        ),
    ]
