# Generated by Django 5.2.5 on 2025-12-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposal', '0002_proposal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='proposal_thumbnails/'),
        ),
    ]
