# Generated by Django 5.2.5 on 2025-12-19 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0012_alter_deliverable_status_alter_milestone_status_and_more'),
        ('Proposal', '0003_proposal_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], db_index=True, default='PENDING', help_text='The current status of this proposal.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['project', 'status'], name='Proposal_pr_project_65ed0d_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['freelancer', 'status'], name='Proposal_pr_freelan_00c44a_idx'),
        ),
    ]
