# Generated by Django 5.2.5 on 2025-11-29 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0010_deliverable'),
        ('User', '0013_alter_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, help_text='Unique order identifier (e.g., ORD-20250129-ABC123)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('IN_PROGRESS', 'Work In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Current order status', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total order amount (sum of all items)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('client', models.ForeignKey(help_text='Client who placed this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, help_text='Associated payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment', to='User.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('SIMPLE', 'Simple Package'), ('MEDIUM', 'Medium Package'), ('EXPERT', 'Expert Package')], help_text='Selected pricing tier', max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Original gig price (from project.budget)', max_digits=10)),
                ('tier_multiplier', models.DecimalField(decimal_places=2, help_text='Pricing multiplier (1.0, 1.5, 2.0)', max_digits=3)),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Calculated price (base_price × tier_multiplier)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(help_text='Freelancer who will fulfill this order', on_delete=django.db.models.deletion.PROTECT, related_name='received_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Order.order')),
                ('project', models.ForeignKey(help_text='Gig being purchased', on_delete=django.db.models.deletion.PROTECT, to='Project.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
