# Generated by Django 5.2.5 on 2025-11-29 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount held in escrow', max_digits=10)),
                ('status', models.CharField(choices=[('HELD', 'Funds Held in Escrow'), ('RELEASED', 'Released to Freelancer'), ('REFUNDED', 'Refunded to Client')], default='HELD', help_text='Current escrow status', max_length=20)),
                ('held_at', models.DateTimeField(auto_now_add=True, help_text='When funds were placed in escrow')),
                ('released_at', models.DateTimeField(blank=True, help_text='When funds were released to freelancer', null=True)),
                ('refunded_at', models.DateTimeField(blank=True, help_text='When funds were refunded to client', null=True)),
                ('order', models.OneToOneField(help_text='Order associated with this escrow', on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='Order.order')),
            ],
            options={
                'verbose_name': 'Escrow',
                'verbose_name_plural': 'Escrows',
                'ordering': ['-held_at'],
            },
        ),
    ]
