# Generated by Django 5.2.5 on 2025-12-19 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_escrow'),
        ('Project', '0011_alter_project_thumbnail'),
        ('User', '0021_fileattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('HELD', 'Funds Held in Escrow'), ('RELEASED', 'Released to Freelancer'), ('REFUNDED', 'Refunded to Client')], db_index=True, default='HELD', help_text='Current escrow status', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('IN_PROGRESS', 'Work In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', help_text='Current order status', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tier',
            field=models.CharField(choices=[('SIMPLE', 'Simple Package'), ('MEDIUM', 'Medium Package'), ('EXPERT', 'Expert Package')], db_index=True, help_text='Selected pricing tier', max_length=10),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['status', 'held_at'], name='Order_escro_status_a4e26e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='Order_order_client__42faa7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='Order_order_status_35f085_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'freelancer'], name='Order_order_order_i_53807e_idx'),
        ),
    ]
