# Generated by Django 5.2.5 on 2025-10-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='delivery_days',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

