# Generated by Django 5.2.7 on 2025-10-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED')], default='OPEN', help_text='The current status of this project', max_length=20),
        ),
    ]
