# Generated by Django 5.2.5 on 2025-10-25 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_alter_project_delivery_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
    ]
