# Generated by Django 5.2.5 on 2025-11-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_remove_project_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('GIG', 'Gig'), ('JOB', 'Job')], default='JOB', help_text='Type of project: GIG (freelancer offers service) or JOB (client needs work done)', max_length=10),
        ),
    ]
