# Generated by Django 5.2.5 on 2025-11-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='List of specific items/tasks for this category (only for Level 2 subcategories)'),
        ),
    ]
