# Generated by Django 5.2.5 on 2025-11-28 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_category_items'),
        ('User', '0013_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_milestones',
            field=models.BooleanField(default=False, help_text='Does this project use milestone-based payments?'),
        ),
        migrations.AddField(
            model_name='project',
            name='milestone_count',
            field=models.IntegerField(default=0, help_text='Total number of milestones'),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone_payment', to='User.payment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='Project.project')),
            ],
        ),
    ]
