# Generated by Django 5.2.5 on 2025-11-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_project_has_milestones_project_milestone_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='has_milestones',
        ),
        migrations.RemoveField(
            model_name='project',
            name='milestone_count',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
