# Generated by Django 5.2.5 on 2025-11-28 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_remove_project_client_remove_project_has_milestones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Freelancer (Owner)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='has_milestones',
            field=models.BooleanField(default=False, help_text='Does this project use milestone-based payments?'),
        ),
        migrations.AddField(
            model_name='project',
            name='milestone_count',
            field=models.IntegerField(default=0, help_text='Total number of milestones'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('GIG', 'Gig'), ('JOB', 'Job')], default='GIG', help_text='Type of project: GIG (freelancer offers service) or JOB (client needs work done)', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED')], default='OPEN', help_text='The current status of this project', max_length=20),
        ),
    ]
