# Generated by Django 5.2.5 on 2025-11-29 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_project_client_project_has_milestones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded deliverable file', upload_to='deliverables/%Y/%m/%d/')),
                ('description', models.TextField(help_text='Description of the submitted work')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Revision Requested')], default='SUBMITTED', help_text='Current review status', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the client reviewed this deliverable', null=True)),
                ('client_feedback', models.TextField(blank=True, help_text="Client's feedback or revision requests")),
                ('freelancer', models.ForeignKey(help_text='Freelancer who submitted this work', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_deliverables', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='The project this deliverable belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='Project.project')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
