# Generated by Django 5.2.5 on 2025-12-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_deliverable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='project_thumbnails/'),
        ),
    ]
