# Generated by Django 5.2.5 on 2025-12-19 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_alter_project_thumbnail'),
        ('User', '0021_fileattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Revision Requested')], db_index=True, default='SUBMITTED', help_text='Current review status', max_length=20),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('GIG', 'Gig'), ('JOB', 'Job')], db_index=True, default='GIG', help_text='Type of project: GIG (freelancer offers service) or JOB (client needs work done)', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED')], db_index=True, default='OPEN', help_text='The current status of this project', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['project', 'status'], name='Project_del_project_ff695f_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['freelancer', 'status'], name='Project_del_freelan_4e95aa_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['project', 'status'], name='Project_mil_project_9f399e_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'project_type'], name='Project_pro_status_20ede7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'status'], name='Project_pro_categor_58145a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client', 'status'], name='Project_pro_client__d1fafc_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='Project_pro_created_71e310_idx'),
        ),
    ]
