# Generated by Django 5.2.5 on 2025-12-06 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_fileattachment'),
        ('message', '0004_alter_message_options_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='User.fileattachment'),
        ),
    ]
