# Generated by Django 5.2.5 on 2025-12-19 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0003_alter_escrow_status_alter_order_created_at_and_more'),
        ('Project', '0012_alter_deliverable_status_alter_milestone_status_and_more'),
        ('Proposal', '0004_alter_proposal_created_at_alter_proposal_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PROPOSAL_SUBMITTED', 'Proposal Submitted'), ('PROPOSAL_ACCEPTED', 'Proposal Accepted'), ('PROPOSAL_REJECTED', 'Proposal Rejected'), ('MESSAGE_RECEIVED', 'Message Received'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_RELEASED', 'Payment Released'), ('ORDER_CREATED', 'Order Created'), ('ORDER_COMPLETED', 'Order Completed'), ('PROJECT_COMPLETED', 'Project Completed'), ('REVIEW_RECEIVED', 'Review Received'), ('SYSTEM_UPDATE', 'System Update')], db_index=True, help_text='Type of notification', max_length=30)),
                ('title', models.CharField(help_text='Notification title/heading', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether notification has been read')),
                ('link_url', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When notification was created')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was marked as read', null=True)),
                ('order', models.ForeignKey(blank=True, help_text='Related order (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
                ('project', models.ForeignKey(blank=True, help_text='Related project (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
                ('proposal', models.ForeignKey(blank=True, help_text='Related proposal (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='Proposal.proposal')),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_f2e0f7_idx')],
            },
        ),
    ]
