# Generated by Django 5.2.5 on 2025-10-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
