# Generated by Django 5.2.5 on 2025-10-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('junior', 'Junior'), ('intermediate', 'Intermediate'), ('senior', 'Senior'), ('expert', 'Expert')], default='beginner', max_length=20, verbose_name='Module Skill Level'),
        ),
    ]
