# Generated by Django 5.2.5 on 2025-10-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_profile_avatar_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
