# Generated by Django 5.2.5 on 2025-10-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='User.role'),
        ),
    ]
