# Generated by Django 5.2.5 on 2025-11-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_populate_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_origin',
            field=models.CharField(max_length=50),
        ),
    ]
