# Generated by Django 5.2.5 on 2025-11-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_user_country_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('HELD', 'Held (Escrow)'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
