# Generated by Django 5.2.5 on 2025-12-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_notificationpreferences_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
