# Generated by Django 5.2.5 on 2025-12-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_alter_user_country_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='preferred_currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code (e.g., USD, EUR, GBP, ZAR)', max_length=3),
        ),
    ]
