# Generated by Django 5.2.5 on 2025-12-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_userpreferences_preferred_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='preferred_currency',
            field=models.CharField(blank=True, default='USD', help_text='ISO 4217 currency code (e.g., USD, EUR, GBP, ZAR)', max_length=3, null=True),
        ),
    ]
