# Generated by Django 5.2.5 on 2025-12-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_alter_userpreferences_preferred_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(blank=True, help_text='Phone country code (e.g., +1, +44, +27)', max_length=10, null=True),
        ),
    ]
