# Generated by Django 5.2.5 on 2025-12-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_user_phone_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when account was deactivated', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='scheduled_deletion_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when account is scheduled for permanent deletion', null=True),
        ),
    ]
