# Generated by Django 5.2.5 on 2025-12-06 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_user_deactivated_at_user_scheduled_deletion_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('profile', 'Profile'), ('portfolio', 'Portfolio'), ('project', 'Project'), ('proposal', 'Proposal'), ('deliverable', 'Deliverable'), ('certification', 'Certification'), ('contract', 'Contract'), ('other', 'Other')], default='other', max_length=20)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('code', 'Code'), ('archive', 'Archive'), ('audio', 'Audio'), ('design', 'Design'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation'), ('other', 'Other')], default='other', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('project_id', models.IntegerField(blank=True, help_text='Related project ID', null=True)),
                ('proposal_id', models.IntegerField(blank=True, help_text='Related proposal ID', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='User_fileat_user_id_280c85_idx'), models.Index(fields=['uploaded_at'], name='User_fileat_uploade_619c8f_idx')],
            },
        ),
    ]
